### ISSUE TITLE
Version recommendation

### ISSUE THREAD

**Issue by jerryorta-dev** [e-oz/ngx-reactive-storage#1]
Love the work.

Since this is an angular-dependent library, I would like to recommend using the same release major version as angular similar to NgRX and Nx. For example, when Angular releases v18, you release v18 as well, which supports Angular 18. You will have to skip a lot of versions, of course, but this is nothing new to the community.

This is the recommended path from the Angular team, and is used by Material, NgRX, Nx... etc. And makes it easier to know if this needs to be updated or not.

**Comment by e-oz** [comment]
Thank you for the idea, but that would mean that I can not make major changes until the new version of Angular is released. Also, that would mean that on every major release of Angular, this library should increment major version number even if there are no breaking changes.

**Comment by jerryorta** [comment]
> Also, that would mean that on every major release of Angular, this library should increment major version number even if there are no breaking changes.

That is correct. That is the Angular standard to keep all libraries in sync and to remove ambiguity of compatibility.

**Comment by e-oz** [comment]
Well, my standard is better.

**Comment by e-oz** [comment]
I could not find any confirmation of your words. And even if I would - I politely explained my decision to you, so I don't see any point in arguing.
