### ISSUE TITLE
🛠️feature request: set method accept generic

### ISSUE THREAD

**Issue by sysmat** [e-oz/ngx-reactive-storage#2]
- It would be nice to parametrize generic method set

```typescript
set<T>(key: string, value: T): Promise<void>;
```

Regards

**Comment by sysmat** [comment]
- https://github.com/sysmat/ngx-reactive-storage
- pro: if set use generic, then you can not pass any value

**Comment by e-oz** [comment]
Thank you for the idea, but I'll have to decline it, sorry. 
A [generic type](https://www.typescriptlang.org/docs/handbook/2/generics.html) is only needed when a function uses this type in the signature of the returned type.
