### ISSUE TITLE
🐛Bug: localForage is missing in ci

### ISSUE THREAD

**Issue by jurck222** [e-oz/ngx-reactive-storage#4]
I  am using **RxLocalStorage** in a service for my application. When i run tests for the said service locally everything is fine and they all pass but when test are run in ci they fail with error message:
```
Error: Module not found: Error: Can't resolve 'localforage'
```
I dont see why i would need **localforage** if i only use **LocalStorage** since it is only used in the **IndexedDB**.

**Comment by e-oz** [comment]
Rewriting the functionality layer provided by localForage just for the sake of tests wouldn't be worth the effort, sorry.

**Comment by sysmat** [comment]
My main mistake when using this lib in my app, I set with wrong value(not typed), so from there come idea. In local storage was looking good, but then when calling get withy generic type was not working properly
